### ISSUE TITLE
Makefile errors 

### ISSUE THREAD

**Issue by Pirater12** [filfat/NinUI#2]
Makefile:1: ***missing separator.Stop

**Comment by filfat** [comment]
Works fine here, can you compile other 3ds homebrew projects?

Also, this https://github.com/filfat/3DS_UI#dont-use-this-like-really

**Comment by Pirater12** [comment]
Other projects just compile fine

**Comment by Pirater12** [comment]
Can you paste the makefile you are using on pastebin might be a issue due to copying from github

**Comment by filfat** [comment]
https://gist.github.com/filfat/bd00c47725fe64e5ca82781ebb79cb0a

**Comment by Pirater12** [comment]
Thanks! This worked :)

**Comment by Pirater12** [comment]
Came across another issue  3DS_UI/Fonts/OpenSans_Regular.h:No such file or directory

**Comment by filfat** [comment]
i dont maintain this anymore, and it never came to a usable state.

Don't remember how I solved that issue and frankly if you're looking to maintain this you should be able to solve it. Sorry.

**Comment by filfat** [comment]
^A little bit just-woke up cranky.

Anyhow, I'm looking into it right now.

**Comment by Pirater12** [comment]
If you camo across something please let me know.

**Comment by filfat** [comment]
@Pirater12 Better late than never..

I have now updated the library to work with the latest ctrulib which should also have fixed the font problem. You'll need to reinstall sf2dlib as we're now using a fork.

Let me know if it works out.
